spring.application.name=backjavaspring

spring.datasource.url=jdbc:postgresql://localhost:5432/postgresLam
spring.datasource.username=postgres
spring.datasource.password=vietnammuonnam123@
spring.docker.compose.enabled=false
