spring.application.name=backjavaspring

spring.datasource.url=jdbc:postgresql://localhost:5432/postgresLam
spring.datasource.username=postgres
spring.datasource.password=vietnammuonnam123@
spring.docker.compose.enabled=false

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG13Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG13Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
server.servlet.context-path=/
