version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: carebridge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vietnammuonnam123@
      POSTGRES_DB: postgresLam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
